export class MockAreasService {
  public areas = [
    {
      "id": 0,
      "name": "Wonderland - Mayhem",
      "description": "Developed since start of 2015. These crags are on the next farm south of Tranquilitas, accessed by a 15 minute easy walk from the Tranquilitas Campsite. Grades range from 10 to 29. Climbing is on compact technical walls and arêtes on amazing quality rock above a valley that is deep and unspoilt. The setting has a ‘wilder’ feel added to by the complete lack of any cellphone signal. Beautiful indigenous trees grow along the base and the crags are quiet except for the sound of the waterfall and the baboons. Climbs are shady earlier than other sectors, most from 9 or 10 onwards except for those at the Animal Farm Sector. The landowner has graciously granted access on the basis that climbers absolutely stick to the following rules: \n\n-ONLY WALK IN BY THE APPROVED ROUTE -KEEP DOGS ON A LEAD AS \nTHERE ARE ANIMALS ON THE FARM -NO FIRES EVER -NO LITTER, \nINCLUDING CIGARETTE BUTTS AND TOILET PAPER -DO NOT WALK IN \nVIEW OF THE FARMHOUSE – DO NOT WALK OUT AFTER DARK…YOU \nMAY BE CONFUSED FOR A THIEF AND SHOT (THIS IS A WORKING FARM) \n",
      "approach": "The walk in has been marked specifically to avoid \ndisturbing the owner, taking a short cut across the hill is absolutely prohibited and \nactually does not save more than a minute or two. Start at the boom gate close to the \ntoilet block at Tranquilitas campsite, walk along the rough track for 250 metres until it \nbends sharply to the left and there is a cairn in the grass. Cut across on grassy track 30 \nmetres to a well-worn mountain bike trail, follow this for 230 metres to a large cairn on \nright and cross grass to obvious place to easily step over the fence (cairns) onto a dirt \nroad. Walk 100 m along the road through wattle trees, when you exit the trees there is a \n‘cow skull’ cairn (maybe the cow skull is still there). From here: \n\n-For the Corruption Crags, from the 'cow-skull cairn', head leftish (north east) towards \nthe cliff top. There is a lovely narrow gully (aka 'Narrow Gully') to walk down. From \nhere the climbs are to the right (facing out). There is no real path and the ground is not \neasy but there looks to be a few good lines. Another option is to abseil into the climbs, \neither from the chains (which can be reached with care, from the top) or by slinging \nboulders. \n\n-For the Burning Man Walls from the ‘cow skull’ cairn, head right (south) following cairns and cattle tracks 450 metres up and down to a flat rock with a cairn by a large wattle tree growing on the cliff top. Hiding behind this tree is an easy scramble down, arriving at the east (right) end of the sector. The path along the base is good. \n\n-For the Animal Farm Crags. These are the crags facing NW on the opposite side of the \nvalley (sunny except early morning and evening) Do not walk over the dam wall as we \nmust not walk on top of the cliffs there. Rather, walk in as for Burning Man Walls to end \nof crag, make your way over the stream just past an old metal pump about 30m down \nfrom the falls, through some thorns. Then up to the crags easily enough. \n"
    },
    {
      "id": 1,
      "name": "Wonderland - Tranquilitas",
      "description": "This is the description ",
      "approach": "This is the approach"
    },
    {
      "id": 2,
      "name": "The Wonderland Crags",
      "description": "This major area is without a doubt the most popular of all with a huge variety of \nclimbing, away from town and with wonderful views. The rise in altitude out of town \nnormally makes this area slightly cooler, assisted by a breeze from the valley below. The \ncrags and climbs are very easy to find and are 5 - 15 minutes walk from the parking. Unless you are staying at Tranquilitas, don’t park there, use the parking at the farmhouse, it’s a shorter walk anyway. \n",
      "approach": "From Boven town: At the main intersection in town, with Roc ‘n Rope Adventures on \nyour left, turn right up the hill past the hospital and past The Elandskrans Mountain \nResort (closed). After a few kilometers the tar road becomes dirt and leads over a \nsmall bridge then up a long hill. After 5 kilometres on the dirt road you can’t miss the \nstone turrets of Tranquilitas. There is a ‘climbers parking’ sign. Park up this track, under \nthe trees. Walk back across the main gravel road and follow the path to the campsite. \nAlternatively, (and only) if you are staying at the Tranquilitas Adventure Farm (chalets, \nperma-tents or camping) you will walk from there. \n\nNote. After heavy rain the dirt road from town can become muddy and unless you have a 4 x 4 you may get stuck. If you’re at the crag and heavy rain looks likely it’s wise to head back to town while you can! The road dries very quickly, normally by 9 am the following day if the rain has stopped. \n"
    }
  ]
}